rvm:
  - 1.9.3
  - 2.0.0
branches:
  only:
      - master
before_script:
  - cp config/config.yml.example config/config.yml
  - bundle exec rake db:create:all
  - bundle exec rake db:migrate
  - bundle exec rake db:migrate HPS_ENV=test
script:
  - bundle exec rake
