rvm:
  - 1.9.3
  - 2.0.0
bundler_args: --without development
branches:
  only:
      - master
before_script:
  - cp config/config.yml.example config/config.yml
  - rake db:create:all
  - rake db:migrate
  - rake db:migrate DS_ENV=test
