rvm:
  - 1.9.3
  - 2.0.0
branches:
  only:
      - master
before_script:
  - cp config/config.yml.example config/config.yml
  - rake db:create:all
  - rake db:migrate
  - rake db:migrate HPS_ENV=test
  # - "export DISPLAY=:99.0"
  # - "sh -e /etc/init.d/xvfb start"
  # - sleep 3 
  # - rackup  # start a Web server
  # - sleep 3
