#!/usr/bin/env ruby
require 'optparse'
 
OPTS = {}
OptionParser.new do |o|
  o.on('-n') { |bool| OPTS[:new] = bool }
  o.on('-e ENVIRONMENT') { |env| OPTS[:environment] = env }
  o.on('-h') { puts o; exit }
  o.parse!
end

ENV['HPS_ENV'] = OPTS[:environment] || 'development'

require_relative '../lib/hps_bioindex'

HpsBioindex.logger = Logger.new($stdout)

if OPTS[:new]
  HpsBioindex::Harvester.nuke
end


timestamp = Item.connection.
  select_value('select max(last_modified) from items') ||
  '1970-01-01'

harvester = HpsBioindex::Harvester.new()

HpsBioindex.conf.communities.each do |community_id|
  harvester.harvest(community_id: community_id, timestamp: timestamp.to_s)  
end 


